packages:
  - 'apps/*' # all packages in apps
  - 'packages/*' # all packages in packages

minimumReleaseAge: 168

minimumDependencyAge: 1

allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  esbuild: true
  prisma: false
  puppeteer: true
  unrs-resolver: false
